/** @type {import('tailwindcss').Config} */
// export default {
  module.exports = {
    content: [
      './**/*.liquid', 
      './css/**/*.{js,ts,jsx,tsx}'
    ],
    theme: {
        extend: {
            fontFamily: {
                 body: ['"elza", sans-serif'],
                 heading: ['"roboto-condensed", sans-serif'],
                 fonticon: ["'Font Awesome 5 Pro'"],
            },
            colors: {
                transparent: 'transparent',
                current: 'currentColor',
                body: '#414141',
                White: '#FFFFFF',
                black: '#000000',
                light_black: '#051C2C',
                blue: '#24ABE2',
                dark_pink1: '#E0198E',
                dark_pink2: '#CA0077',
                dark_pink3: '#AA0064',
                yellow: '#F1EB5F',
                gray: '#E0E0E0',
                light_grey: '#F4F4F4',
            },
            flex: {
                auto: '1 1 auto',
                initial: '0 1 auto',
                inherit: 'inherit',
                none: 'none',
            },
            boxShadow: {
                'shadow-xl': '0px 4px 0px 0px #A93800;', 
                'shadow-hover-xl': '0px 4px 0px 0px #F8FF00;',
                'shadow-2xl': '0px 4px 20px 0px #00000033;',
                'shadow-orange': '0px 4px 0px 0px #F06700;', 
            },
            letterSpacing: {
                normal: '0',
              },
            container: {
                center: true,
                padding: '20px',
            },
            zIndex: {
                '-1': '-1',
                0: 0,
                1: 1,
                2: 2,
                9: 9,
                11: 11,
                12: 12,
                98: 98,
                99: 99,
                100: 100,
                900: 900,
                999: 999,
                9999: 9999,
            },
            padding: {
              0: '0px',
              1: '1px',
              2: '2px',
              4: '4px',
              5: '5px',
              6: '6px',
              7: '7px',
              8: '8px',
              9: '9px',
              10: '10px',
              11: '11px',
              12: '12px',
              13: '13px',
              14: '14px',
              15: '15px',
              16: '16px',
              17: '17px',
              20: '20px',
              25: '25px',
              28: '28px',
              30: '30px',
              35: '35px',
              40: '40px',
              50: '50px',
              55: '55px',
              60: '60px',
              70: '70px',
              80: '80px',
              100: '100px',
              200: '200px',
              300: '300px',
            },
            margin: {
              0: '0px',
              2: '2px',
              3: '3px',
              4: '4px',
              5: '5px',
              6: '6px',
              8: '8px',
              9: '9px',
              10: '10px',
              13: '13px',
              14: '14px',
              15: '15px',
              20: '20px',
              25: '25px',
              28: '28px',
              30: '30px',
              35: '35px',
              40: '40px',
              55: '55px',
              70: '70px',
              80: '80px',
              100: '100px',
            },
            fontSize: {
              8: '8px',
              9: '9px',
              10: '10px',
              11: '11px',
              12: '12px',
              13: '13px',
              14: '14px',
              15: '15px',
              16: '16px',
              17: '17px',
              18: '18px',
              20: '20px',
              22: '22px',
              24: '24px',
              26: '26px',
              28: '28px',
              30: '30px',
              32: '32px',
              36: '36px',
              38: '38px',
              42: '42px',
              40: '40px',
              44: '44px',
              48: '48px',
              50: '50px',
              64: '64px',
            },
            lineHeight: {
              0: '0px',
              9: '9px',
              14: '14px',
              20: '20px',
              22: '22px',
              24: '24px',
              26: '26px',
              28: '28px',
              31: '31px',
              32: '32px',
              36: '36px',
              42: '42px',
              46: '46px',
              56: '56px',
              63: '63px',
              75: '75px',
            },
            gap: {
              5: '5px',
              10: '10px',
              14: '14px',
              15: '15px',
              16: '16px',
              20: '20px',
              25: '25px',
              28: '28px',
              30: '30px',
              35: '35px',
              40: '40px',
              44: '44px',
              50: '50px',
              55: '55px',
              100: '100px',
            },
            width: {
                1: '1px',
                2: '2px',
                3: '3px',
                4: '4px',
                8: '8px',
                9: '9px',
                10: '10px',
                12: '12px',
                15: '15px',
                20: '20px',
                40: '40px',
            },
            height: {
                1: '1px',
                2: '2px',
                3: '3px',
                4: '4px',
                7: '7px',
                8: '8px',
                10: '10px',
                12: '12px',
                15: '15px',
                20: '20px',
                40: '40px',
            },
            minWidth: {
                1: '1px',
            },
            maxWidth: {
                1: '1px',
            },
            minHeight: {
                auto: 'auto',
            },
            maxHeight: {
                auto: 'auto',
            },
            inset: {
                0: '0px',
                1: '1px',
                2: '2px',
                3: '3px',
                4: '4px',
                5: '5px',
                7: '7px',
                8: '8px',
                9: '9px',
                10: '10px',
                20: '20px',
                25: '25px',
                28: '28px',
                40: '40px',
                55: '55px',
                60: '60px',
                70: '70px',
                90: '70px',
                100: '100px',
                "50_per": '50%',
                "100_per": '100%',
            },
            borderWidth: {
                DEFAULT: '1px',
                1: '1px',
                2: '2px',
                3: '3px',
                4: '4px',
                5: '5px',
                0: '0px',
            },
            borderRadius: {
                DEFAULT: '1px',
                0: '0px',
                1: '1px',
                2: '2px',
                3: '3px',
                4: '4px',
                5: '5px',
                10: '10px',
                14: '14px',
                20: '20px',
                23: '23px',
                24: '24px',
               
            },
            textUnderlineOffset: {
                DEFAULT: '1px',
                1: '1px',
                2: '2px',
                3: '3px',
                4: '4px',
                5: '5px',
            },
            ransitionProperty: {
                'height': 'height',
            },
            transitionDelay: {
                '1': '1ms',
                '2': '0.2s',
            },
            outline: {
                none: 'none',
            },
              textIndent: {
                '-9999': '-9999px',
            },
            backgroundImage: (theme) => ({
                none: "none",
                bg_gradient_white:"linear-gradient(90deg, rgba(255, 255, 255, 0.6) 0%, rgba(255, 255, 255, 0) 50%);",
                bg_gradient_orange:"linear-gradient(90deg, rgba(255,237,48,1) 0%, rgba(240,103,0,1) 100%);",
                bg_gradient_green: "linear-gradient(90deg, rgba(248,255,0,1) 0%, rgba(69,123,0,1) 100%);",
                bg_gradient_brown: "linear-gradient(90deg, rgba(169,56,0,1) 0%, rgba(47,20,9,1) 100%);",
            }),
            backgroundSize: {
                '15px': '15px 20px'
            },
            backgroundPosition: {
                'right-center': '95% 51%',
                'right-center1': '100% 51%',
            },
            screens: {
                // Mobile First
                xsscreen: { 'max': '320px' },
                xxsscreen1: { 'max': '374px' },
                xsscreen1: { 'min': '375px' },
                xsscreen2: { 'max': '400px' },
                xsscreen3: { 'min': '401px' },
                smscreen: { 'max': '575px' },
                smscreen1: { 'min': '576px' },
                smscreen2: { 'max': '639px' },
                // Tablet First
                mdscreen5: { 'max': '749px' },
                mdscreen4: { 'min': '750px' },
                mdscreen: { 'max': '767px' },
                mdscreen1: { 'max': '989px' },
                mdscreen3: { 'max': '991px' },
                mdscreen2: { 'min': '990px' },
                lgscreen: { 'max': '1023px' },
                xlscreen: { 'max': '1199px' },
                xlscreen1: { 'min': '1200px' },
                xlscreen2: { 'max': '1279px' },
                // Desktop First
                xl: { 'min': '1280px' },
                small_desktop1: { 'max': '1365px' },
                small_desktop: { 'min': '1366px' },
                desktop: { 'min': '1440px' },
                large_desktop: { 'min': '1512px' },
                midlarge_desktop: { 'min': '1600px' },
                extlarge_desktop: { 'min': '1921px' },
            }
        },
      },
    plugins: [
        function ({ addComponents }) {
            addComponents({
                '.container': {
                    maxWidth: '100%',
                    '@screen sm': {
                        maxWidth: '640px',
                    },
                    '@screen md': {
                        maxWidth: '768px',
                    },
                    '@screen lg': {
                        maxWidth: '940px',
                    },
                    '@screen xl': {
                        maxWidth: '1240px',
                    },
                    '@screen 2xl': {
                        maxWidth: '1512px',
                    },
                }
            })
        }
    ],
  }